title: Alexandra Marie Website for you
markdown: kramdown
# url: ""
# baseurl: "https://aleriveraa08.github.io/"

# for atom feed
author:
  name: Alexandra Rivera
  email: alexa08rivera@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
